version: '3.3'
services:

  jupyter:
    image: dbmi/r-datascience-notebook:nhanes-pic-sure-notebook-development-only-August-20-2018
    restart: always
    networks:
      - public
    expose:
      - 8888
    ports:
      - 80:8888
    volumes:
      - ./jupyter-notebooks-working/jupyter-notebooks:/home/jovyan/work
  copy-working-files:
    image: alpine:latest
    entrypoint: cp -r jupyter-notebooks/ jupyter-notebooks-working
    volumes:
      - ./jupyter-notebooks:/jupyter-notebooks
      - ./jupyter-notebooks-working:/jupyter-notebooks-working
networks:
  public:



