version: '3.3'
services:

  jupyter:
    image: dbmi/r-datascience-notebook:nhanes-pic-sure-notebook-development-only-August-20-2018
    restart: always
    networks:
      - public
    expose:
      - 8888
    ports:
      - 80:8888
    volumes:
      - ./jupyter-notebooks:/home/jovyan/work

networks:
  public:



